# GitHub Pages config

title: Mastodon TypeScript Library
description: TypeScript Library for the Mastodon API
author: Â© TypeScriptLibs and Contributors
email: bug@typescriptlibs.org
github_username:  typescriptlibs
rss: rss

show_excerpts: false

github:
  private: true

header_pages:
  - SECURITY.md
  - LICENSE.md
  - _config.md

include:
  - LICENSE.md
  - _config.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

theme: minima

minima:
  date_format: "%Y-%m-%d"
  skin: classic

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
